### ISSUE TITLE
There is a bug.

### ISSUE THREAD

**Issue by Perezari** [fredatgithub/FamilyShow#1]
When I drag a picture of a person into the window, I get an error.
Can you fix it?

**Comment by fredatgithub** [comment]
What is your error message ?

**Comment by fredatgithub** [comment]
Can you join a screen  capture ?

**Comment by fredatgithub** [comment]
I cannot reproduce the bug
Can you describe each step in order for me to reproduce the bug ?

**Comment by fredatgithub** [comment]
bug reproduced

**Comment by fredatgithub** [comment]
Bug fixed in version 3.2
