### ISSUE TITLE
Como usar? How to use?

### ISSUE THREAD

**Issue by williamfrezze** [fredatgithub/FamilyShow#4]
Boa tarde.

Como utilizo este programa? Basta fazer download? Não localizei o arquivo .exe.

Agradecido.

-----  

Good afternoon.

How do I use this program? Just download? I couldn't find the .exe file.

Grateful.

**Comment by fredatgithub** [comment]
hello,
go to
https://github.com/fredatgithub/FamilyShow/releases
download FamilyShow-Release-V3.4.zip file
unzip it in a folder in your documents
Go inside this folder and double-click on FamilyShow.exe
Click on the New menu
Add a first member of a family, e.g. you
Add other persons of your family.


You can also download a sample family 
Go to the Sample Windsor Familly section between V3.0 and V3.1
Download  the file: **Family.Show-samplesWindsor_familly.zip** 
unzip it to your folder
With the application, open this file: **Windsor.family**
Now you can see the Windsor family and add royal members if you like.

**Comment by fredatgithub** [comment]
download FamilyShow-Release-V3.4.zip package and not the source code
Extract the zip file and you will find the exe application file
