### ISSUE TITLE
Windows Store?

### ISSUE THREAD

**Issue by plettb** [fredatgithub/FamilyShow#5]
Have you ever considered publishing this app to the Windows Store?  I'd be open to helping with such an endeavor. :)

Do you know own the intellectual property?  I assume that would be the biggest question to be answered before it could be published to the store.

**Comment by michmela44** [comment]
Search "My Family Tree" in the Windows Store.

A company already took the Family.Show code and did this in 2017, and subsequently quit updating it

**Comment by michmela44** [comment]
They did continue to update the main application though

https://chronoplexsoftware.com/myfamilytree/updates/versionhistory.htm

**Comment by fredatgithub** [comment]
hello,
No, I have not considered publishing this app to the Windows Store.
Thanks for your help.
I don't own the intellectual property because I've copied the code from Codeplex. I use MIT copyright.
I didn't know about My Family Tree, interesting.
